# Generated by Django 6.1 on 2026-09-13 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_company_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('formal-edu', 'Formal-Edu'), ('certifiaction', 'Certifiaction'), ('course-bootcamp', 'Course-Bootcamp'), ('academic-project', 'Academic-project'), ('award-honor', 'Award-Honor')], default='full-time', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
