# Generated by Django 6.1 on 2026-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('formal-edu', 'Formal-Edu'), ('certification', 'Certification'), ('course-bootcamp', 'Course-Bootcamp'), ('academic-project', 'Academic-project'), ('award-honor', 'Award-Honor')], default='formal-edu', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(),
        ),
    ]
