# Generated by Django 6.1 on 2026-09-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
