# Generated by Django 6.1 on 2026-09-14 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('soft', 'Soft Skill'), ('technical', 'Technical Skill')], default='technical', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
