# Generated by Django 6.1 on 2026-09-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order']},
        ),
    ]
